### PR TITLE
Replace ts() with E::ts()

### PR DESCRIPTION
**Pull request by lucky091588**

### CODE REVIEW

**Comment by lucky091588** [comment]
I need help testing the changes since I don't know where to check it on the browser.

**Comment by twomice** [comment]
@lucky091588 Actually this one is not displayed in the browser, because there is no settings form. But it will be run -- and any errors should appear -- when clearing civicrm caches, as with `cv flush` or the "Cleanup Caches" button. From looking at the code, I believe you will see an error due to missing `E` class definition.

**Comment by lucky091588** [comment]
@twomice After installing the extension and flush the cache. I don't see any `E` error. Can you recheck the changes?

**Comment by twomice** [comment]
@lucky091588 I'm seeing this error on cv flush:

First I checkout master and call cv flush: no errors.
Then I checkout lucky/replace_ts and get the error: `Class 'E' not found`. Here's the terminal output:

```
✔ /var/www/d7civi47latest/sites/default/files/civicrm/ext/com.joineryhq.profcond [:6dd77b9|✔] 
10:51 $ git checkout master 
Previous HEAD position was 6dd77b9... Replace ts() with E::ts()
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
✔ /var/www/d7civi47latest/sites/default/files/civicrm/ext/com.joineryhq.profcond [master|✔] 
10:51 $ cv flus
Flushing system caches
✔ /var/www/d7civi47latest/sites/default/files/civicrm/ext/com.joineryhq.profcond [master|✔] 
10:51 $ git checkout lucky/replace_ts                                                                                                                                                             
Note: checking out 'lucky/replace_ts'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 6dd77b9... Replace ts() with E::ts()
✔ /var/www/d7civi47latest/sites/default/files/civicrm/ext/com.joineryhq.profcond [:6dd77b9|✔] 
10:51 $ cv flush
Flushing system caches

                                                           
  [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Class 'E' not found                                      
                                                           

flush [-T|--triggers] [--level LEVEL] [-t|--test] [-U|--user USER]

```

The solution would be to add `use CRM_Profcond_ExtensionUtil as E;` at the top of profcond.setting.php. Can you make that change?

**Comment by lucky091588** [comment]
@twomice My bad, I forgot that this is on another branch. Anyway, please check latest update. Thanks.

**Comment by twomice** [comment]
merged, thanks @lucky091588

**Pull request merged**
